'use client';
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixrmqnvccehystergtwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cm1xbnZjY2VoeXN0ZXJndHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTEzNzMsImV4cCI6MjA2MzIyNzM3M30.TSeGCNe5pm2EHBKaYZPQLsDtFVFaDObiAaGqKt7NQhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);